### ISSUE TITLE
able to remove deployed vehicles

### ISSUE THREAD

**Issue by rustydev19** [rusty1909/Navigator#16]
add vehicle -> go to waiting tab -> setup the vehicle -> press delete vehicle in portal

vehicle is getting deleted which should not happen
please apply a check of deployed state while deleting

@dheerajagrawal19  please take care of this

**Comment by dheerajagrawal19** [comment]
try now
beside this there is no option of removing vehicle when it is deployed

**Comment by rustydev19** [comment]
commit # 9da6aa6b4609a74f9ad223f6c256b9f72ee52810 added
