### ISSUE TITLE
Data is not Synchronize . 

### ISSUE THREAD

**Issue by sumshri** [rusty1909/Navigator#18]
My ID is sumshri .
My device is on with location and proper 3G network . But data is fetching proper in portal . It is taking more time near about 1 hour and 10 min . Please resolve the issue .

**Comment by rustydev19** [comment]
@sumshri  please ellaborate

**Comment by sumshri** [comment]
I am not able to find to present location of device.

**Comment by rustydev19** [comment]
@sumshri  please check on some other system, coz its working fine in here.

**Comment by rustydev19** [comment]
fixed in new tracking app
