### ISSUE TITLE
Registration page issue 

### ISSUE THREAD

**Issue by sumshri** [rusty1909/Navigator#31]
Hi Team ,

We have created new user ID - raja . But my account is not activated . Because I am not getting link in our mail id .
my mail is id is sumitcse2008@hamil.com
Please check for the same .

**Comment by sumshri** [comment]
HI Team ,
Please work on reported issue because many of user is facing same issue . 
Thank u

**Comment by dheerajagrawal19** [comment]
i think by default account is active, and they should also receive mail
