### ISSUE TITLE
In company Registation page issue 

### ISSUE THREAD

**Issue by sumshri** [rusty1909/Navigator#35]
If I am registering company details on company registration page .Than my I am getting some error like 
( sorry some  error accrued ) But I don't to which option is wrong in form . 
Please help us ..fill the form in easy method .... 
Thank u ....

**Comment by dheerajagrawal19** [comment]
r u still facing this issue, if yes let us know the full scenario

**Comment by rusty1909** [comment]
@sumshri please check the issue again,

**Comment by sumshri** [comment]
As of now I am not observing reported issue . You can close this issue. If again issue will happen .We will log issue for this same .......
Thank u ..
