### ISSUE TITLE
Vehicle List issue 

### ISSUE THREAD

**Issue by sumshri** [rusty1909/Navigator#38]
Hi Team ,

My user id is sumshri . I have Vehicle .I want to remove some Vehicle from vehicle list .  But I am not able do for this same . Please check and do the needful .

Thank U ....

**Comment by sumshri** [comment]
Hi Team ,

My user id is sumshri . I have 4 Vehicle .I want to remove some Vehicle from vehicle list . But I am not able do for this same . Please help us .

Thank U ....

**Comment by rusty1909** [comment]
if the vehicle is already deployed with device, it cant be deleted from the portal directly,
this is a feature to keep control over the deployed vehicles

if vehicle is in waiting state, it can be deleted with ease
