### ISSUE TITLE
FG - Payment and settings tab issue 

### ISSUE THREAD

**Issue by sumshri** [rusty1909/Navigator#44]
Hi Team ,

Basic information tab is working on Company details page . But Payment and settings option is not working . Need to work on reported issue .
Please check and do the needful .

Thank u ...

**Comment by rusty1909** [comment]
@dheerajagrawal19  please check

**Comment by dheerajagrawal19** [comment]
payments part done...

**Comment by dheerajagrawal19** [comment]
this part can't be tested but it can be enhanced with  suggestion
