### ISSUE TITLE
FG - I am not able to delete driver name 

### ISSUE THREAD

**Issue by sumshri** [rusty1909/Navigator#50]
Hi Team ,

FG - I am not able to delete driver name  from our list of driver name.
Thank U ....

**Comment by rusty1909** [comment]
delete feature is not added to driver list to prevent the condition on which the owner delete the driver by mistake without clearing all the due payments,
so the delete feature will be added later on when complete detail of driver is created and the button will be enabled only when all the pending payments are cleared.
