### ISSUE TITLE
images not available in activation mail

### ISSUE THREAD

**Issue by rusty1909** [rusty1909/Navigator#52]
images not available in activation mail
and hyperlink issue is also present

@dheerajagrawal19 please check

**Comment by dheerajagrawal19** [comment]
forward me that mail

**Comment by dheerajagrawal19** [comment]
Fixed hyperlink one

**Comment by rusty1909** [comment]
@dheerajagrawal19  mail forwarded

**Comment by dheerajagrawal19** [comment]
images are already there, in mail you need to download these images
