### ISSUE TITLE
not able to make changes

### ISSUE THREAD

**Issue by rusty1909** [rusty1909/Navigator#54]
product info is showing blank,
so not able to make payment

@dheerajagrawal19 please check

**Comment by rusty1909** [comment]
@dheerajagrawal19 
any update on the issue??

**Comment by dheerajagrawal19** [comment]
please elablorate scenario with attachments

**Comment by rusty1909** [comment]
login with my credentials 
rusty
rusty

**Comment by dheerajagrawal19** [comment]
when no amount to pay, pay now button will be disabled at payment page....
we can take advance but we need to handle those scenarios.....
one solution is allow him to modify payment box and check is amount payable or take the amount in multiple of a parameter.,
