### ISSUE TITLE
vehicle addition mail content

### ISSUE THREAD

**Issue by rusty1909** [rusty1909/Navigator#55]
Make year is coming with current year

Vehicle Type : Truck 
Vehicle Model : ashok 
Make Year: Sep 07, 2015 

only year should come

@dheerajagrawal19 please check

**Comment by dheerajagrawal19** [comment]
fixed, only yearly part should come...

**Comment by rusty1909** [comment]
not fixed
@dheerajagrawal19 please check

**Comment by rusty1909** [comment]
fixed
